In [1]:
import pandas as pd

In [2]:

# Load the Wikipedia page
url = "https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table"
tables = pd.read_html(url)

# Assuming the third table is the one with the all-time medal data
medal_table = tables[2]  # Adjust this index if necessary

pd.set_option('display.max_rows', 100)
medal_table

,Team (IOC code),No. Summer,No. Winter,No. Games
0,American Samoa (ASA),10,2,12
1,Andorra (AND),13,13,26
2,Angola (ANG),11,0,11
3,Antigua and Barbuda (ANT),12,0,12
4,Aruba (ARU),10,0,10
5,Bangladesh (BAN),11,0,11
6,Belize (BIZ)[BIZ],14,0,14
7,Benin (BEN)[BEN],13,0,13
8,Bhutan (BHU),11,0,11
9,Bolivia (BOL),16,7,23
10,Bosnia and Herzegovina (BIH),9,8,17
11,British Virgin Islands (IVB),11,2,13
12,Brunei (BRU)[A],7,0,7
13,Cambodia (CAM),11,0,11
14,Cayman Islands (CAY),12,2,14
15,Central African Republic (CAF),12,0,12
16,Chad (CHA),14,0,14
17,Comoros (COM),8,0,8
18,Republic of the Congo (CGO),14,0,14
19,Democratic Republic of the Congo (COD)[COD],12,0,12
20,Cook Islands (COK),10,0,10
21,El Salvador (ESA),13,0,13
22,Eswatini (SWZ)[SWZ],12,1,13
23,Equatorial Guinea (GEQ),11,0,11
24,The Gambia (GAM),11,0,11
25,Guam (GUM),10,1,11
26,Guinea (GUI),13,0,13
27,Guinea-Bissau (GBS),8,0,8
28,Honduras (HON),13,1,14
29,Kiribati (KIR),6,0,6
30,Laos (LAO),11,0,11
31,Lesotho (LES),13,0,13
32,Liberia (LBR)[C],14,0,14
33,Libya (LBA)[D],12,0,12
34,Madagascar (MAD),14,3,17
35,Malawi (MAW),12,0,12
36,Maldives (MDV),10,0,10
37,Mali (MLI),15,0,15
38,Malta (MLT),18,3,21
39,Marshall Islands (MHL),5,0,5
40,Mauritania (MTN),11,0,11
41,Federated States of Micronesia (FSM),7,0,7
42,Monaco (MON)[N],22,11,33
43,Myanmar (MYA)[MYA],19,0,19
44,Nauru (NRU),8,0,8
45,Nepal (NEP)[a],15,4,19
46,Nicaragua (NCA),14,0,14
47,Oman (OMA),11,0,11
48,Palau (PLW),7,0,7
49,Palestine (PLE),8,0,8
50,Papua New Guinea (PNG),12,0,12
51,Rwanda (RWA),11,0,11
52,Saint Kitts and Nevis (SKN),8,0,8
53,Saint Vincent and the Grenadines (VIN),10,0,10
54,São Tomé and Príncipe (STP),8,0,8
55,Seychelles (SEY),11,0,11
56,Sierra Leone (SLE),13,0,13
57,Solomon Islands (SOL),11,0,11
58,Somalia (SOM),11,0,11
59,South Sudan (SSD),3,0,3
60,East Timor (TLS)[I],6,3,9
61,Tuvalu (TUV),5,0,5
62,Vanuatu (VAN),10,0,10
63,Yemen (YEM)[YEM],9,0,9
64,Korea (COR),0,1,1
65,Malaya (MAL)[MAL],2,0,2
66,North Borneo (NBO)[NBO],1,0,1
67,Republic of China (ROC)[ROC],3,0,3
68,Saar (SAA)[SAA],1,0,1
69,North Yemen (YAR)[YAR],2,0,2
70,South Yemen (YMD)[YMD],1,0,1

In [3]:
name_with_country_codes = medal_table["Team (IOC code)"]

def get_country_code(country):
    return country[country.find("(")+1:country.find(")")]


stripped_country_codes = name_with_country_codes.map(get_country_code)

In [7]:
name_with_country_codes

0                            American Samoa (ASA)
1                                   Andorra (AND)
2                                    Angola (ANG)
3                       Antigua and Barbuda (ANT)
4                                     Aruba (ARU)
5                                Bangladesh (BAN)
6                               Belize (BIZ)[BIZ]
7                                Benin (BEN)[BEN]
8                                    Bhutan (BHU)
9                                   Bolivia (BOL)
10                   Bosnia and Herzegovina (BIH)
11                   British Virgin Islands (IVB)
12                                Brunei (BRU)[A]
13                                 Cambodia (CAM)
14                           Cayman Islands (CAY)
15                 Central African Republic (CAF)
16                                     Chad (CHA)
17                                  Comoros (COM)
18                    Republic of the Congo (CGO)
19    Democratic Republic of the Congo (COD)[COD]
20                             Cook Islands (COK)
21                              El Salvador (ESA)
22                            Eswatini (SWZ)[SWZ]
23                        Equatorial Guinea (GEQ)
24                               The Gambia (GAM)
25                                     Guam (GUM)
26                                   Guinea (GUI)
27                            Guinea-Bissau (GBS)
28                                 Honduras (HON)
29                                 Kiribati (KIR)
30                                     Laos (LAO)
31                                  Lesotho (LES)
32                               Liberia (LBR)[C]
33                                 Libya (LBA)[D]
34                               Madagascar (MAD)
35                                   Malawi (MAW)
36                                 Maldives (MDV)
37                                     Mali (MLI)
38                                    Malta (MLT)
39                         Marshall Islands (MHL)
40                               Mauritania (MTN)
41           Federated States of Micronesia (FSM)
42                                Monaco (MON)[N]
43                             Myanmar (MYA)[MYA]
44                                    Nauru (NRU)
45                                 Nepal (NEP)[a]
46                                Nicaragua (NCA)
47                                     Oman (OMA)
48                                    Palau (PLW)
49                                Palestine (PLE)
50                         Papua New Guinea (PNG)
51                                   Rwanda (RWA)
52                    Saint Kitts and Nevis (SKN)
53         Saint Vincent and the Grenadines (VIN)
54                    São Tomé and Príncipe (STP)
55                               Seychelles (SEY)
56                             Sierra Leone (SLE)
57                          Solomon Islands (SOL)
58                                  Somalia (SOM)
59                              South Sudan (SSD)
60                            East Timor (TLS)[I]
61                                   Tuvalu (TUV)
62                                  Vanuatu (VAN)
63                               Yemen (YEM)[YEM]
64                                    Korea (COR)
65                              Malaya (MAL)[MAL]
66                        North Borneo (NBO)[NBO]
67                   Republic of China (ROC)[ROC]
68                                Saar (SAA)[SAA]
69                         North Yemen (YAR)[YAR]
70                         South Yemen (YMD)[YMD]
Name: Team (IOC code), dtype: object

In [10]:
type(stripped_country_codes)

pandas.core.series.Series

In [9]:
stripped_country_codes.to_csv("wiki_country_codes.csv")